bigfile/py: Starting from py3.11 exception state is kept only in exc_value no longer using exc_type and exc_traceback
    bigfile/_bigfile.c: In function ‘pybigfile_loadblk’:
    bigfile/_bigfile.c:616:56: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      616 |     XINC( save_exc_type           = set0(&ts->exc_state.exc_type)       );
          |                                                        ^

exc_type and exc_traceback can all be derived from exc_value.
See https://github.com/python/cpython/commit/396b58345f81 and
https://github.com/python/cpython/issues/89874 for details.

-> Rework the code to only use exc_value on py ≥ 3.11 .

/reviewed-by @jerome
/reviewed-on https://lab.nexedi.com/nexedi/wendelin.core/-/merge_requests/37