wcfs: tests: Test WCFS CLI
https://lab.nexedi.com/nexedi/wendelin.core/-/merge_requests/38 attempts
to fix bugs introduced with https://lab.nexedi.com/nexedi/wendelin.core/-/commit/e51bef0d26eb.
We didn't see these bugs in test results, because the WCFS CLI codepath
is not covered in our tests. This patch adds coverage of this codepath
to increase the likelihood that issues are quickly detected.

--------
kirr: Rework original Levin's patch not to pollute global state of test
process with e.g. glog logging setup. Original patch is here:
https://lab.nexedi.com/levin.zimmermann/wendelin.core/-/commit/3cb3872fd1e2

Added test currently fails with

    wcfs/wcfs_test.py::test_wcfs_main
    Exception in subprocess wcfs.wcfs_test._test_wcfs_main (pid936172):
    Traceback (most recent call last):
      File "/home/kirr/src/wendelin/wendelin.core/wcfs/internal/multiprocessing.py", line 84, in _start
        r = f(*argv, **kw)
      File "wcfs/wcfs_test.py", line 2047, in _test_wcfs_main
        wcfs.main()
      File "<decorator-gen-42>", line 2, in main
      File "/home/kirr/src/tools/go/pygolang/golang/__init__.py", line 166, in _goframe
        return f(*argv, **kw)
      File "/home/kirr/src/wendelin/wendelin.core/wcfs/__init__.py", line 1108, in main
        glog.basicConfig(stream=sys.stderr, level=logging.INFO)
      File "/home/kirr/src/wendelin/wendelin.core/wcfs/internal/glog.py", line 36, in basicConfig
        logging.setLogRecordFactory(LogRecord)
    AttributeError: 'module' object has no attribute 'setLogRecordFactory'

    ...

            zurl = "file://abc"
            _("serve",  ("-arg0", zurl),
    >                   (zurl, ("-arg0",)))

    ...

            if end.exc is not None:
    >           raise end.exc
    E           AttributeError: 'module' object has no attribute 'setLogRecordFactory'

it will be fixed by the next patch.