bigfile/py: PyThreadState->frame is no longer directly available on py3.11
    bigfile/_bigfile.c: In function ‘pybigfile_loadblk’:
    bigfile/_bigfile.c:594:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?
      594 |     ts_frame_orig = ts->frame;  // just for checking
          |                         ^~~~~
          |                         cframe

https://docs.python.org/3/whatsnew/3.11.html says to replace access with PyThreadState_GetFrame().

/reviewed-by @jerome
/reviewed-on https://lab.nexedi.com/nexedi/wendelin.core/-/merge_requests/37