tests: Don't forget to depend on ccan's config.h
Else, in a clean repo the tests do not build from scratch:

    $ make test
    x86_64-linux-gnu-gcc -pthread -g -Wall -D_GNU_SOURCE -std=gnu99 -fplan9-extensions -Wno-declaration-after-statement -Wno-error=declaration-after-statement  -Iinclude -I3rdparty/ccan -I3rdparty/include   bigfile/tests/test_virtmem.c lib/bug.c lib/utils.c 3rdparty/ccan/ccan/tap/tap.c  -o bigfile/tests/test_virtmem.t
    In file included from include/wendelin/list.h:11:0,
                     from include/wendelin/bigfile/virtmem.h:33,
                     from bigfile/tests/../virtmem.c:23,
                     from bigfile/tests/test_virtmem.c:21:
    3rdparty/ccan/ccan/array_size/array_size.h:4:20: fatal error: config.h: No such file or directory
     #include "config.h"
                        ^
    compilation terminated.
    3rdparty/ccan/ccan/tap/tap.c:26:20: fatal error: config.h: No such file or directory
     #include "config.h"
                        ^
    compilation terminated.
    Makefile:99: recipe for target 'bigfile/tests/test_virtmem.t' failed
    make: *** [bigfile/tests/test_virtmem.t] Error 1