tox/ZODB3: Limit ZConfig < 3.2.0
With ZConfig==3.2.0 (released 2017-06-22) ZEO started to get file names
as unicode, which eventually breaks on assert in ZODB3.FileStorage code:

    Traceback (most recent call last):
      File "/home/kirr/src/wendelin/r/work/venv/local/lib/python2.7/site-packages/ZEO/tests/zeoserver.py", line 215, in <module>
        main()
      File "/home/kirr/src/wendelin/r/work/venv/local/lib/python2.7/site-packages/ZEO/tests/zeoserver.py", line 188, in main
        server = ZEO.runzeo.create_server({"1": storage}, zo)
      File "/home/kirr/src/wendelin/r/work/venv/local/lib/python2.7/site-packages/ZEO/runzeo.py", line 366, in create_server
        auth_realm = options.auth_realm,
      File "/home/kirr/src/wendelin/r/work/venv/local/lib/python2.7/site-packages/ZEO/StorageServer.py", line 890, in __init__
        self._setup_invq(name, storage)
      File "/home/kirr/src/wendelin/r/work/venv/local/lib/python2.7/site-packages/ZEO/StorageServer.py", line 928, in _setup_invq
        self.invq[name] = list(lastInvalidations(self.invq_bound))
      File "/home/kirr/src/wendelin/r/work/venv/local/lib/python2.7/site-packages/ZODB/FileStorage/FileStorage.py", line 1238, in lastInvalidations
        for trans in FileIterator(self._file_name, pos=pos)]
      File "/home/kirr/src/wendelin/r/work/venv/local/lib/python2.7/site-packages/ZODB/FileStorage/FileStorage.py", line 1640, in __init__
        assert isinstance(filename, str), `filename`
    AssertionError: u'/home/kirr/src/wendelin/r/work/wendelin.core/Data.fs'

-> So for ZODB3 pin ZConfig to ZConfig <3.2.0 which is known to work with ZODB3.