tox: Fix the breakage
I accidently broke tox setup with c5e18c74 (bigfile/zodb: Teach ZBigFile
backend to use WCFS) and adding }} at tail instead of properly closing
the numpy section. As the result event `tox -l` was breaking with:

    py37-ZODB5-auto-zeo-numpy116-{!wcfs} failed with ConfigError: substitution key '!wcfs' not found at Traceback (most recent call last):
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1299, in run
        results[name] = cur_self.make_envconfig(name, section, subs, config)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1479, in make_envconfig
        res = meth(env_attr.name, env_attr.default, replace=replace)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1701, in getpath
        path = self.getstring(name, defaultpath, replace=replace)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1818, in getstring
        x = self._replace_if_needed(x, name, replace, crossonly)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1834, in _replace_if_needed
        x = self._replace(x, name=name, crossonly=crossonly)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1861, in _replace
        replaced = Replacer(self, crossonly=crossonly).do_replace(value)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1901, in do_replace
        expanded = substitute_once(value)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1895, in substitute_once
        return self.RE_ITEM_REF.sub(self._replace_match, x)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1968, in _replace_match
        return self._replace_substitution(sub_value)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 2003, in _replace_substitution
        val = self._substitute_from_other_section(sub_key)
      File "/home/kirr/src/wendelin/venv/z-dev/lib/python2.7/site-packages/tox/config/__init__.py", line 1998, in _substitute_from_other_section
        raise tox.exception.ConfigError("substitution key {!r} not found".format(key))
    ConfigError: ConfigError: substitution key '!wcfs' not found

-> Fix that.