wcfs: Add tests to show WCFS kills dead or dying clients
When a WCFS client doesn't respond to a pin request in time, the server
attempts to kill it [1]. However, there are cases where the client may
stop for unrelated reasons (e.g. being restarted by another program)
after the pin request is sent. In such situations, WCFS should not
forcefully kill the client, as this leads to misleading logs suggesting
the client was faulty, when in fact it was simply restarted.

This commit adds tests that reproduce these scenarios and verify
that WCFS only kills clients when truly necessary.

Note: these tests currently fail, as WCFS still kills dead or dying clients.

[1] https://lab.nexedi.com/nexedi/wendelin.core/-/commit/c559ec1a9

--------
kirr:

- use os._exit instead of sys.exit to simulate OS-level process kill
- add 2·pinkill sleep before verifying that the process was not pinkilled by wcfs
- mark added test with xfail
- don't duplicate code
- cosmetics

Added test currently fails as e.g.

    INFO     wcfs:__init__.py:301 starting for file:///tmp/testdb_fs.01bOZy/1.fs ...
    I1110 15:21:59.221350 2938668 wcfs.go:2754] start "/dev/shm/wcfs/5d8d6942d7f39fa05fe1024e4c8a8c21a44e1254" "file:///tmp/testdb_fs.01bOZy/1.fs"
    I1110 15:21:59.221419 2938668 wcfs.go:2760] (built with go1.25.4)
    W1110 15:21:59.221546 2938668 15:21] 9.221542 zodb: FIXME: open file:///tmp/testdb_fs.01bOZy/1.fs: raw cache is not ready for invalidations -> NoCache forced
    INFO     wcfs:__init__.py:343 started pid2938668 @ /dev/shm/wcfs/5d8d6942d7f39fa05fe1024e4c8a8c21a44e1254

    M: commit -> @at1 (0404bfc5fd8b75ee)
    M:      f<0000000000000010>     [2]

    M: commit -> @at2 (0404bfc5fdadfd00)
    M:      f<0000000000000010>     [2]

    C: setup watch f<0000000000000010> @at1 (0404bfc5fd8b75ee)
    #  pinok: {2: @at1 (0404bfc5fd8b75ee)}
    E1110 15:22:00.463181 2938668 wcfs.go:1603] pid2938691: client failed to handle pin notification correctly and timely in 3s: pin #2 @0404bfc5fd8b75ee: sendReq: waiting for reply: context canceled
    E1110 15:22:00.463203 2938668 wcfs.go:1603] pid2938691: -> killing it because else 1) all other clients will remain stuck, and 2) we no longer can provide correct data to the faulty client.
    E1110 15:22:00.463209 2938668 wcfs.go:1603] pid2938691:    (see "Protection against slow or faulty clients" in wcfs description for details)
    E1110 15:22:00.463217 2938668 wcfs.go:1642] pid2938691: <- SIGBUS
    E1110 15:22:00.463394 2938668 wcfs.go:1603] pid2938691: terminated
    E1110 15:22:00.463420 2938668 wcfs.go:2085] wlink 1: serve rx: unexpected EOF
    >>> Change history by file:

    f<0000000000000010>:
                                    0 1 2 3 4 5 6 7
                                    a b c d e f g h
            @at0 (0404bfc5fca35122)
            @at1 (0404bfc5fd8b75ee)     2
            @at2 (0404bfc5fdadfd00)     2

    INFO     wcfs:__init__.py:418 unmount/stop wcfs pid2938668 @ /dev/shm/wcfs/5d8d6942d7f39fa05fe1024e4c8a8c21a44e1254
    I1110 15:22:09.606301 2938668 wcfs.go:2942] stop "/dev/shm/wcfs/5d8d6942d7f39fa05fe1024e4c8a8c21a44e1254" "file:///tmp/testdb_fs.01bOZy/1.fs"
    FAILED

    ============================================ FAILURES =============================================
    ___________________ test_wcfs_pinhfaulty_kill_on_watch[_bad_watch_stop_on_pin] ____________________

    faulty = <function _bad_watch_stop_on_pin at 0x7f45ee31aad0>, with_prompt_pintimeout = None

        @mark.parametrize('faulty', [
            _bad_watch_no_pin_read,
            _bad_watch_no_pin_reply,
            _bad_watch_stop_on_pin,
            _bad_watch_eof_pin_reply,
            _bad_watch_nak_pin_reply,
        ])
        @func
        def test_wcfs_pinhfaulty_kill_on_watch(faulty, with_prompt_pintimeout):
            t = tDB(multiproc=True); zf = t.zfile
            defer(t.close)

            at1 = t.commit(zf, {2:'c1'})
            at2 = t.commit(zf, {2:'c2'})
            f = t.open(zf)
            f.assertData(['','','c2'])

            # launch faulty process that should be killed by wcfs on problematic pin during watch setup
            p = tFaultySubProcess(t, faulty, at=at1)
            defer(p.close)
            t.assertStats({'pinkill': 0})

            # wait till faulty client issues its watch, receives pin and pauses/misbehaves
            p.send("start watch")
            if faulty != _bad_watch_no_pin_read:
                assert p.recv(t.ctx) == b"pin %s #%d @%s" % (h(zf._p_oid), 2, h(at1))

            # issue our watch request - it should be served well and without any delay
            wl = t.openwatch()
            wl.watch(zf, at1, {2:at1})

            # the faulty client must become killed by wcfs
            # but client that stops itself, must not be killed
            must_kill = (faulty != _bad_watch_stop_on_pin)
            if not must_kill:
                # give time to wcfs to detect wlink close and potentially initiate pinkill
                # do not wait on the process yet, so it remains in the OS process table in Z state
                xsleep(t.ctx, 2*t.pintimeout)
            p.join(t.ctx)
            assert p.exitcode is not None
    >       t.assertStats({'pinkill': int(must_kill)})

    wcfs_faultyprot_test.py:213:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    t = <wendelin.wcfs.wcfs_test.tDB object at 0x7f45edf9dd70>, kvok = {'pinkill': 0}

        def assertStats(t, kvok):
            # kstats loads stats subset with kvok keys.
            def kstats():
                stats = t._loadStats()
                kstats = {}
                for k in kvok.keys():
                    kstats[k] = stats.get(k, None)
                return kstats

            # wait till stats reaches expected state
            ctx = timeout()
            while 1:
                kv = kstats()
                if kv == kvok:
                    break
                if ctx.err() is not None:
    >               assert kv == kvok, "stats did not reach expected state"
    E               AssertionError: stats did not reach expected state
    E               assert {'pinkill': 1} == {'pinkill': 0}
    E                 Differing items:
    E                 {'pinkill': 1} != {'pinkill': 0}
    E                 Full diff:
    E                 - {'pinkill': 1}
    E                 ?             ^
    E                 + {'pinkill': 0}
    E                 ?             ^

    wcfs_test.py:478: AssertionError

Original patch: https://lab.nexedi.com/levin.zimmermann/wendelin.core/-/commit/8d3fa76d

/reviewed-by @kirr
/reviewed-on https://lab.nexedi.com/nexedi/wendelin.core/-/merge_requests/33