wcfs: multiprocessing: Fix process spawning when sys.path is set dynamically
When using pip-installed packages, the Python interpreter automatically
sets up sys.path to include the necessary modules. However, in cases
where sys.path is modified dynamically within a script (e.g., to include
local or non-installed modules), spawned child processes do not inherit
this custom path by default.

This leads to failures when child processes attempt to import modules
that are only available through the parent's modified sys.path.
In WCFS, this issue occurs if 'wendelin.core' is not installed via pip
but instead added dynamically in a script. As a result, invoking the
WCFS CLI (e.g., with the 'status' command) from within such a script
fails [1]

This fix ensures that the dynamically modified sys.path is properly
propagated to child processes, resolving import errors in these scenarios.

[1] >>> ./wcfs status <zurl>
I0609 10:25:53.098927 1048343 __init__.py:610] wcfs: status <zurl> ...
ok - mount entry: /dev/shm/wcfs/ea94c11195da31e3232dad5ca6321e421a58101d  (0:41)
ok - wcfs server: pid110075 slapuser77 wcfs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named wendelin.wcfs.internal
fail - stat mountpoint: 'NoneType' object has no attribute 'st_dev'
Traceback (most recent call last):
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/bin/wcfs", line 300, in <module>
    sys.exit(wendelin.wcfs.main())
  File "<decorator-gen-42>", line 2, in main
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/pygolang/golang/__init__.py", line 166, in _goframe
    return f(*argv, **kw)
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/wendelin.core/wcfs/__init__.py", line 1119, in main
    status(zurl)
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/wendelin.core/wcfs/__init__.py", line 684, in status
    verify("stat mountpoint", os.stat, mnt.point, retcheck=_)
  File "<decorator-gen-43>", line 2, in verify
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/pygolang/golang/__init__.py", line 166, in _goframe
    return f(*argv, **kw)
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/wendelin.core/wcfs/__init__.py", line 676, in verify
    fail("%s: %s" % (subj, exc))
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/wendelin.core/wcfs/__init__.py", line 616, in fail
    raise RuntimeError('(failed)')
RuntimeError: (failed)