setup: Fix for py3
py2-only syntax introduced in acf7e91d (setup/runcmd: Properly report
errors, if running command is missing):

      File "setup.py", line 168
        except Exception, e:
                        ^
    SyntaxError: invalid syntax