wcfs: multiprocessing: Fix spawning process if sys.path is dynamically set
When using 'pip', the python executable itself provides the modules and
packages contexts as 'sys.path'. However, when relying on a script that
sets 'sys.path' dynamically, spawning processes may fail in this script
if the spawned processes do not explicitly set the same 'sys.path' as
their parent - then the child process may not find imported modules and
simply fail. In the context of WCFS, this is currently happening if
'wendelin.core' isn't installed via pip, but explicitly dynamically set
inside a script via 'sys.path'. Then, when calling the WCFs python CLI
inside this script, the 'status' command fails:

>>> ./wcfs status <zurl>
I0609 10:25:53.098927 1048343 __init__.py:610] wcfs: status <zurl> ...
ok - mount entry: /dev/shm/wcfs/ea94c11195da31e3232dad5ca6321e421a58101d  (0:41)
ok - wcfs server: pid110075 slapuser77 wcfs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named wendelin.wcfs.internal
fail - stat mountpoint: 'NoneType' object has no attribute 'st_dev'
Traceback (most recent call last):
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/bin/wcfs", line 300, in <module>
    sys.exit(wendelin.wcfs.main())
  File "<decorator-gen-42>", line 2, in main
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/pygolang/golang/__init__.py", line 166, in _goframe
    return f(*argv, **kw)
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/wendelin.core/wcfs/__init__.py", line 1119, in main
    status(zurl)
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/wendelin.core/wcfs/__init__.py", line 684, in status
    verify("stat mountpoint", os.stat, mnt.point, retcheck=_)
  File "<decorator-gen-43>", line 2, in verify
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/pygolang/golang/__init__.py", line 166, in _goframe
    return f(*argv, **kw)
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/wendelin.core/wcfs/__init__.py", line 676, in verify
    fail("%s: %s" % (subj, exc))
  File "/srv/slapgrid/slappart77/srv/runner/software/cedb008e052c42f1d64abbdca52e4f06/parts/wendelin.core/wcfs/__init__.py", line 616, in fail
    raise RuntimeError('(failed)')
RuntimeError: (failed)