wcfs: os: Fix Proc.fd to handle EPERM properly
While reviewing the previous patch I noticed that Proc.fd misbehaves
when there is permission error:

    ---- 8< ---- (x.py)
    from wendelin.wcfs.internal import os as xos
    pdbc = xos.ProcDB.open()
    ---- 8< ----

    (neo) (py311.venv) (g.env) kirr@deca:~/src/neo/src/lab.nexedi.com/nexedi/wendelin.core$ python x.py
    Traceback (most recent call last):
      File "/home/kirr/src/wendelin/wendelin.core/x.py", line 3, in <module>
        pdbc = xos.ProcDB.open()
               ^^^^^^^^^^^^^^^^^
      File "/home/kirr/src/wendelin/venv/py311.venv/lib/python3.11/site-packages/decorator.py", line 235, in fun
        return caller(func, *(extras + args), **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kirr/src/tools/go/pygolang-master/golang/__init__.py", line 166, in _goframe
        return f(*argv, **kw)
               ^^^^^^^^^^^^^^
      File "/home/kirr/src/wendelin/wendelin.core/wcfs/internal/os.py", line 330, in open
        proc.get(name)
      File "/home/kirr/src/wendelin/venv/py311.venv/lib/python3.11/site-packages/decorator.py", line 235, in fun
        return caller(func, *(extras + args), **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kirr/src/tools/go/pygolang-master/golang/__init__.py", line 166, in _goframe
        return f(*argv, **kw)
               ^^^^^^^^^^^^^^
      File "/home/kirr/src/wendelin/wendelin.core/wcfs/internal/os.py", line 590, in get
        v = eraise(v)
            ^^^^^^^^^
      File "/home/kirr/src/wendelin/wendelin.core/wcfs/internal/os.py", line 544, in eraise
        raise e
      File "/home/kirr/src/wendelin/wendelin.core/wcfs/internal/os.py", line 563, in get
        v = f(proc)
            ^^^^^^^
      File "/home/kirr/src/wendelin/wendelin.core/wcfs/internal/os.py", line 704, in fd
        ifd.pos     = int(e.pop("pos"))
                          ^
    UnboundLocalError: cannot access local variable 'e' where it is not associated with a value

The problem happens because Proc.fd, like many other methods catches
OSError+IOError to see if it was transient ENOENT, but forgets to
reraise the exception if it was not.

-> Fix that.

I also checked all other places that do such OSErrror+IOError filtering
and Proc.fd was the only one to miss to reraise.

Thorough tests for ProcDB and MountDB are still TODO.

Fixes 7932bac5 (wcfs: os: Add ProcDB & co)

/reviewed-by @levin.zimmermann
/reviewed-on https://lab.nexedi.com/nexedi/wendelin.core/-/merge_requests/40#note_237564